CREATE SCHEMA IF NOT EXISTS public;

ALTER SCHEMA public OWNER TO pg_database_owner;

COMMENT ON SCHEMA public IS 'standard public schema';

SET default_tablespace = '';

SET default_table_access_method = heap;

-- ============================================================
-- projects（プロジェクト情報の静的テーブル）
-- ============================================================

CREATE TABLE IF NOT EXISTS public.projects (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id bigint GENERATED BY DEFAULT AS IDENTITY (
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ) NOT NULL,
    display_name text NOT NULL,
    created_at date
);

ALTER TABLE public.projects OWNER TO postgres;

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_display_name_key UNIQUE (display_name);

COMMENT ON TABLE public.projects IS 'プロジェクト情報の静的テーブル';

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- activity_logs（CLIから登録したユーザーアクティビティの動的テーブル）
-- ============================================================

CREATE TABLE IF NOT EXISTS public.activity_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    project_id uuid NOT NULL,
    commit_hash_digest text NOT NULL,
    lines_added smallint DEFAULT 0 NOT NULL,
    lines_deleted smallint DEFAULT 0 NOT NULL,
    xp_earned integer DEFAULT 0 NOT NULL,
    committed_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.activity_logs OWNER TO postgres;

ALTER TABLE ONLY public.activity_logs
    ADD CONSTRAINT activity_logs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.activity_logs
    ADD CONSTRAINT activity_logs_commit_hash_digest_key UNIQUE (commit_hash_digest);

ALTER TABLE ONLY public.activity_logs
    ADD CONSTRAINT activity_logs_project_id_key UNIQUE (project_id);

ALTER TABLE ONLY public.activity_logs
    ADD CONSTRAINT activity_logs_user_id_key UNIQUE (user_id);

ALTER TABLE ONLY public.activity_logs
    ADD CONSTRAINT activity_logs_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.activity_logs
    ADD CONSTRAINT activity_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

COMMENT ON TABLE public.activity_logs IS 'CLIから登録したユーザーアクティビティの動的テーブル';

ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- api_keys（apiキーの静的テーブル）
-- ============================================================

CREATE TABLE IF NOT EXISTS public.api_keys (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid DEFAULT gen_random_uuid() NOT NULL,
    key_hash text NOT NULL,
    name text NOT NULL,
    last_used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.api_keys OWNER TO postgres;

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_key_hash_key UNIQUE (key_hash);

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

COMMENT ON TABLE public.api_keys IS 'apiキーの静的テーブル';

ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- rewards（報酬の静的テーブル）
-- ============================================================

CREATE TABLE IF NOT EXISTS public.rewards (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    description text,
    required_xp integer NOT NULL,
    daily_limit smallint DEFAULT 1 NOT NULL,
    repeat_type text DEFAULT 'daily' NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.rewards OWNER TO postgres;

ALTER TABLE ONLY public.rewards
    ADD CONSTRAINT rewards_pkey PRIMARY KEY (id);

COMMENT ON TABLE public.rewards IS '報酬の静的テーブル';

ALTER TABLE public.rewards ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- reward_logs（報酬へのXP投入履歴の動的テーブル）
-- ============================================================

CREATE TABLE IF NOT EXISTS public.reward_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    reward_id uuid NOT NULL,
    xp_amount bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.reward_logs OWNER TO postgres;

ALTER TABLE ONLY public.reward_logs
    ADD CONSTRAINT reward_logs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.reward_logs
    ADD CONSTRAINT reward_logs_reward_id_fkey FOREIGN KEY (reward_id) REFERENCES public.rewards(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.reward_logs
    ADD CONSTRAINT reward_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

COMMENT ON TABLE public.reward_logs IS '報酬へのXP投入履歴の動的テーブル';

ALTER TABLE public.reward_logs ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- reward_unlock_logs（報酬の解放履歴の動的テーブル）
-- ============================================================

CREATE TABLE IF NOT EXISTS public.reward_unlock_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    reward_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.reward_unlock_logs OWNER TO postgres;

ALTER TABLE ONLY public.reward_unlock_logs
    ADD CONSTRAINT reward_unlock_logs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.reward_unlock_logs
    ADD CONSTRAINT reward_unlock_logs_reward_id_fkey FOREIGN KEY (reward_id) REFERENCES public.rewards(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.reward_unlock_logs
    ADD CONSTRAINT reward_unlock_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

COMMENT ON TABLE public.reward_unlock_logs IS '報酬の解放履歴の動的テーブル';

ALTER TABLE public.reward_unlock_logs ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 権限設定
-- ============================================================

GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.projects TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.projects TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.projects TO service_role;

GRANT ALL ON SEQUENCE public.projects_user_id_seq TO anon;
GRANT ALL ON SEQUENCE public.projects_user_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.projects_user_id_seq TO service_role;

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.activity_logs TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.activity_logs TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.activity_logs TO service_role;

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.api_keys TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.api_keys TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.api_keys TO service_role;

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.rewards TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.rewards TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.rewards TO service_role;

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.reward_logs TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.reward_logs TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.reward_logs TO service_role;

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.reward_unlock_logs TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.reward_unlock_logs TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.reward_unlock_logs TO service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO service_role;
